// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package authsqlc

import (
	"database/sql"
	"time"
)

type AuthPasswordCredential struct {
	UserID       string
	PasswordHash string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type AuthSession struct {
	ID        string
	UserID    string
	TokenHash string
	UserAgent string
	IpAddress string
	ExpiresAt time.Time
	RevokedAt sql.NullTime
	CreatedAt time.Time
}

type User struct {
	ID              string
	Email           string
	Status          string
	EmailVerifiedAt sql.NullTime
	CreatedAt       time.Time
	UpdatedAt       time.Time
}
