// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package authsqlc

import (
	"context"
	"database/sql"
	"time"
)

const createSession = `-- name: CreateSession :one
INSERT INTO auth_sessions (
    id,
    user_id,
    token_hash,
    user_agent,
    ip_address,
    expires_at,
    created_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, user_id, token_hash, user_agent, ip_address, expires_at, revoked_at, created_at
`

type CreateSessionParams struct {
	ID        string
	UserID    string
	TokenHash string
	UserAgent string
	IpAddress string
	ExpiresAt time.Time
	CreatedAt time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (AuthSession, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.UserAgent,
		arg.IpAddress,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.UserAgent,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM auth_sessions
WHERE expires_at < $1
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context, expiresAt time.Time) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredSessions, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, user_id, token_hash, user_agent, ip_address, expires_at, revoked_at, created_at FROM auth_sessions
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetSessionByID(ctx context.Context, id string) (AuthSession, error) {
	row := q.db.QueryRowContext(ctx, getSessionByID, id)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.UserAgent,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT id, user_id, token_hash, user_agent, ip_address, expires_at, revoked_at, created_at FROM auth_sessions
WHERE token_hash = $1
LIMIT 1
`

func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash string) (AuthSession, error) {
	row := q.db.QueryRowContext(ctx, getSessionByTokenHash, tokenHash)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.UserAgent,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const revokeAllSessionsForUser = `-- name: RevokeAllSessionsForUser :exec
UPDATE auth_sessions
SET revoked_at = $2
WHERE user_id = $1
  AND revoked_at IS NULL
`

type RevokeAllSessionsForUserParams struct {
	UserID    string
	RevokedAt sql.NullTime
}

func (q *Queries) RevokeAllSessionsForUser(ctx context.Context, arg RevokeAllSessionsForUserParams) error {
	_, err := q.db.ExecContext(ctx, revokeAllSessionsForUser, arg.UserID, arg.RevokedAt)
	return err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE auth_sessions
SET revoked_at = $2
WHERE id = $1
`

type RevokeSessionParams struct {
	ID        string
	RevokedAt sql.NullTime
}

func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) error {
	_, err := q.db.ExecContext(ctx, revokeSession, arg.ID, arg.RevokedAt)
	return err
}
